### ISSUE TITLE
table_load_wizard.mp4 not loading 

### ISSUE THREAD

**Issue by sebastiandres** [acarson510/streamlit-wizard-form#1]
The table_load_wizard.mp4 video is. not loading - link appears to be wrong. The other videos are ok.
(BTW: Great idea and superb execution, I'll be stealing this wizard idea for all my future projects!)

**Comment by acarson510** [comment]
Thank you, apologies, I have not looked in awhile. Hopefully the code helped out. I think the link works, but just takes a few seconds to load bc larger file? Thanks again for looking. If possible, please just let me know if still can't see so I can fix for everyone.

**Comment by sebastiandres** [comment]
Hi! I'm pretty sure I tested the link before creating the issue, but anyway, glad it's fixed. Closing the issue!
